name: CI
on:
  push:
    branches:
      - master # need to filter here so we only deploy when there is a push to master


jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.repos.createPagesSite({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
